# Generated by Django 3.2 on 2021-05-04 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20210425_0616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typepost',
            options={'ordering': ['title'], 'verbose_name': 'Тип статьи', 'verbose_name_plural': 'Типы статей'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aвтор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aвтор'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aвтор'),
        ),
    ]
