# Generated by Django 3.2 on 2021-05-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210504_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
